### PR TITLE
support other query params on geocode

### PR DESCRIPTION
**Pull request by walker**
support other query params on geocode, right now, that'd be "fields" but they could add others later, I'd imagine.

### CODE REVIEW

**Comment by walker** [comment]
Is there something I should handle differently here?

I can submit a patch that takes a different tack to supporting this, if you have one in mind...

**Comment by walker** [comment]
Desmond: Would you be willing to transfer or add me to this module so that I can merge the PR and continue maintenance?

**Comment by desmondmorris** [comment]
@walker sorry for delay.  Thanks for working on this.  I will get this merged and into a release.

I think moving forward with this package, it may make sense to do away with the resource specific convenience methods in favor of something more manageable.  I will track here: https://github.com/desmondmorris/node-geocodio/issues/7

**Comment by walker** [comment]
:+1:

**Pull request merged**
